### PR TITLE
Clarify that a numeric timezone must be "-07:00"

### PR DESCRIPTION
**Pull request by xuhdev**

### CODE REVIEW

**Comment by xuhdev** [comment]
I'm guessing this is true based on https://github.com/gohugoio/hugo/issues/12495#issuecomment-2111509436?

I'm also thinking that removing "America/Los_Angeles" can reduce confusion...

**Comment by jmooring** [comment]
This is incorrect. Those are examples of parsable values, not layout strings, and the offset can be anything. Again, I think there's a conceptual disconnect here. The layout string is described here:

<https://gohugo.io/functions/time/format/#layout-string>

**Comment by xuhdev** [comment]
Just wanna make sure I understand it right: If the layout string contains a timezone offset, it must be "-7:00". Is this correct?

**Comment by jmooring** [comment]
As described here...

<https://gohugo.io/methods/time/format/#layout-string>

...it can be any of these:

image

**Pull request closed without merging**
