### PR TITLE
Add hreflang Tag to Translation Link example

### PR DESCRIPTION
**Pull request by ZhangChengLin**
https://developer.mozilla.org/en-US/docs/web/html/element/a#hreflang

### CODE REVIEW

**Comment by ZhangChengLin** [comment]
https://deploy-preview-2396--gohugoio.netlify.app/methods/page/translations/

https://deploy-preview-2396--gohugoio.netlify.app//methods/page/alltranslations/

**Comment by jmooring** [comment]
I suggest this instead:

```

  <ul>
    {{ range . }}
      {{ $langName := or .Language.LanguageName .Language.Lang }}
      {{ $langCode := or .Language.LanguageCode .Language.Lang }}
      <li><a href="{{ .RelPermalink }}" hreflang="{{ $langCode }}">{{ .LinkTitle }} ({{ $langName }})</a></li>
    {{ end }}
  </ul>

```

The language config may not contain either `.LanguageName` or `.LanguageCode`.

**Comment by ZhangChengLin** [comment]
> I suggest this instead:
> 
> ```
> 
>   <ul>
>     {{ range . }}
>       {{ $langName := or .Language.LanguageName .Language.Lang }}
>       {{ $langCode := or .Language.LanguageCode .Language.Lang }}
>       <li><a href="{{ .RelPermalink }}" hreflang="{{ $langCode }}">{{ .LinkTitle }} ({{ $langName }})</a></li>
>     {{ end }}
>   </ul>
> ```
> 
> The language config may not contain either `.LanguageName` or `.LanguageCode`.


I did write it like you did at first, but later I found that based on the context configured in this page of the document, the current way of writing should be enough.
I do think the way you provided is more complete, and I would like to write it that way in my own site code.
If you think that's the only way to accept a PR, I'm willing to adjust.

**Comment by jmooring** [comment]
Please make the change as suggested.

**Comment by ZhangChengLin** [comment]
> Please make the change as suggested.


The modifications have been completed according to the suggested writing method.

**Comment by jmooring** [comment]
Thank you.

**Pull request merged**
