### PR TITLE
Update merge function examples

### PR DESCRIPTION
**Pull request by jmooring**
Supersedes #1641
Closes #1641

### CODE REVIEW

**Comment by davidsneighbour** [comment]
I still don't get this: "Merge creates a copy of the final `MAP` and merges any preceding `MAP` into it in reverse order." Doesn't that mean, `{{ $merged.x }}   --> foo` in regards to the first sample? I am not sure if I have a brain-freeze here... that language to me (non-native english speaker) means "merge a b c" is c, then merging b into it, then merging a into it. The "reverse order" seems to be the issue for me. Maybe it means the right thing, but the order of the words in that sentence make it hard to understand?

**Comment by jmooring** [comment]
@davidsneighbour I haven't merged this yet, but note that I added the sentence, "Merging adds elements to the final map; it does not update existing elements." The examples are accurate. I have documented how it currently behaves, but I'm not thrilled about the description.

**Comment by jmooring** [comment]
@davidsneighbour Also remember that these are equivalent:

```
{{ merge $m2 $m1 }}
{{ $m1 | merge $m2 }}
```

**Comment by jmooring** [comment]
This describes how the result is obtained internally with `tpl/collections/merge.go`:

> Merge creates a copy of the final `MAP` and merges any preceding `MAP` into it in reverse order. Merging _adds_ elements to the final map; it does not _update_ existing elements.

Although this is technically correct, I think it makes more sense to describe what it does from the user's perspective:

> Returns the result of merging the given maps from left to right. If a key already exists, `merge` updates its value. If a key is absent, `merge` inserts the value under the new key.

**Pull request merged**
