### PR TITLE
fix typo error

### PR DESCRIPTION
**Pull request by yajiez**
Just a small typo error.

### CODE REVIEW

**Comment by anthonyfok** [comment]
> Git Commit Message Guidelines
>
> ... the most important part being that each commit message should have a title/subject in imperative mood **starting with a capital letter** and no trailing period

**Comment by yajiez** [comment]
Hi, anthonyfok. I just read Git Commit Message Guidelines after my pull request, sorry. I have never created pull request before, but I will do much better in the future.

Thanks for your guidance again.

**Comment by anthonyfok** [comment]
Thank you for your contribution, @yajiez!  Good catch!

However, I did have to change your git commit message to fit the contribution guidelines.  Your original message had a two problems:

    fix typo error
    
    Just a small typo error.

1. The word "fix" should start with a capital letter, i.e., "Fix", according to the contribution guidelines.
2. The second line of text of the commit message doesn't add any new information and thus redundant and unnecessary.

I changed it the following:

    Fix double "your" typo in taxonomies.md

though I think your original message "Fix typo" with a capital "F" would do just fine.  :-)

If you haven't read it yet, the blog article https://chris.beams.io/posts/git-commit/ offers great advice on writing Git commit messages and on writing changelogs in general.

Many thanks for your contribution!

**Comment by yajiez** [comment]
Hi, the blog article you recommended is great. I have used Git for several years but haven't learned how to writing Git commit messages and changelogs. 

Many thanks for your help!

**Pull request merged**
