### PR TITLE
Fix typo in RenderString.md

### LINKED ISSUE #1019: Typo? :REND on .RenderString samples
The samples on https://gohugo.io/functions/renderstring/ show the following:

```
{{ $optBlock := dict "display" "block" }}
{{ $optOrg := dict "markup" "org" }}
{{ "**Bold Markdown**" | $p.RenderString }}
{{  "**Bold Block Markdown**" | $p.RenderString  $optBlock }}
{{  "/italic org mode/" | $p.RenderString  $optOrg }}:REND
```

The `:REND` in the last line is nowhere explained. I feel like this might be a typo? If not, we should add some notes about this.

### PR DESCRIPTION
**Pull request by davidsneighbour**
Fixes #1019

### CODE REVIEW

**Comment by davidsneighbour** [comment]
I am not going to merge this because it's my own pull request ;)

**Comment by bep** [comment]
>I am not going to merge this because it's my own pull request ;)

Me neither ... a typo with change in 37 files. I was sure that I had removed the "image action" ... It is all my fault, but I cannot merge this PR as is.

**Comment by davidsneighbour** [comment]
oops, could it come from my branch?

**Comment by bep** [comment]
>oops, could it come from my branch?

No it comes from a stupid image GitHub action that adds commits ... I have now deleted it (for the second time, I think), but I'm not sure what to do with this PR ... Simplest to maybe fix the typo in another PR:

**Pull request closed without merging**
