### PR TITLE
Add Hugo wrapper

### PR DESCRIPTION
**Pull request by khos2ow**
This PR is to add [hugo-wrapper](https://github.com/khos2ow/hugo-wrapper), a universal way to use Hugo binary anywhere:

- to `tools/starter-kits` page
- to the whole repository itself (as a showcase of how it works)

### CODE REVIEW

**Comment by khos2ow** [comment]
tail of Netlify logs:

```
3:30:45 PM: Executing user command: ./hugow --buildFuture -b $DEPLOY_PRIME_URL
3:30:45 PM: downloading hugo binary version v0.46 ...
3:30:47 PM: [done]
3:30:47 PM: verifying hugo binary version v0.46 .....
3:30:47 PM: [done]
3:30:47 PM: unzipping hugo binary version v0.46 .....
3:30:47 PM: [done]
3:30:47 PM: Building sites …
3:30:50 PM: 
3:30:50 PM:                    | EN  | ZH
3:30:50 PM: +------------------+-----+-----+
3:30:50 PM:   Pages            | 521 |  23
3:30:50 PM:   Paginator pages  |   1 |   0
3:30:50 PM:   Non-page files   |  37 |   0
3:30:50 PM:   Static files     | 166 | 166
3:30:50 PM:   Processed images |  81 |   0
3:30:50 PM:   Aliases          |  15 |   4
3:30:50 PM:   Sitemaps         |   2 |   1
3:30:50 PM:   Cleaned          |   0 |   0
3:30:50 PM: Total in 2282 ms
3:30:50 PM: Caching artifacts
3:30:50 PM: Started saving pip cache
3:30:50 PM: Finished saving pip cache
3:30:50 PM: Started saving emacs cask dependencies
3:30:50 PM: Finished saving emacs cask dependencies
3:30:50 PM: Started saving maven dependencies
3:30:50 PM: Finished saving maven dependencies
3:30:50 PM: Started saving boot dependencies
3:30:50 PM: Finished saving boot dependencies
3:30:50 PM: Started saving go dependencies
3:30:50 PM: Finished saving go dependencies
3:30:50 PM: Build script success
3:30:50 PM: Starting to deploy site from 'public'
3:31:10 PM: Starting post processing
3:31:53 PM: Finished processing build request in 1m28.505776015s
3:32:15 PM: Invalid header directives:
3:32:15 PM: - /_headers: /*
	*/
3:32:15 PM: Post processing done
3:32:15 PM: Site is live
```

**Comment by kaushalmodi** [comment]
You need to open an issue to explain the rationale of this big of a change. Why is this wrapper needed for the hugoDocs site? The site build works without it too.

**Comment by bep** [comment]
>You need to open an issue to explain the rationale of this big of a change.

Yes, please start with an issue.

**Comment by khos2ow** [comment]
I added it to the build script, merely as a showcase of how it works so it's totally fine to me to revert that back.
But, this was the main reason I started putting together the wrapper script in the first place, to have a consistence, reproducible, platform-independent way of using Hugo binary.

**Comment by kaushalmodi** [comment]
> I added it to the build script, merely as a showcase of how it works

Right, though there's no need to add this for building the doc site.

Feel free to create a separate repo for your tool and link it [here][1].

[1]: https://gohugo.io/tools/other/

**Comment by khos2ow** [comment]
That's what I did [here](https://deploy-preview-562--gohugoio.netlify.com/tools/starter-kits/) in this PR (924e732) and that's why I pushed them in two separate commits.

**Comment by kaushalmodi** [comment]
> That's what I did here in this PR

No. You committed your script source too.

Your PR might be accepted after review if it contains only a link to your script repo, with brief description (see how others share their tools on HugoDocs). 

HugoDocs cannot contain its full source as it will not use it (and so also cannot take up the ownership/maintainership of it).

**Comment by kaushalmodi** [comment]
That first commit would be fine. You can create a new PR with just that.

**Comment by khos2ow** [comment]
Sure, I understand. I have already removed the script and forced push to the branch, but since this PR is closed it's not reflecting the new change.

**Comment by khos2ow** [comment]
Opened a new PR #563 .

**Pull request closed without merging**
