### PR TITLE
Remove misplaced note in Hugo functions docs

### PR DESCRIPTION
**Pull request by rhcarvalho**
Remove misplaced note about `hugo.Generator`.

### CODE REVIEW

**Comment by jmooring** [comment]
I think you should just remove the note.

By default, Hugo's injects something like this into the home page:
<meta name="generator" content="Hugo 0.111.3">

**Comment by rhcarvalho** [comment]
Is the part that says "The generator tag allows the Hugo team to track the usage and popularity of Hugo" accurate?

If you feel like the note is not providing any value I'm okay with removing it altogether.

**Comment by jmooring** [comment]
> Is the part that says "The generator tag allows the Hugo team to track the usage and popularity of Hugo" accurate?

Indirectly via https://builtwith.com/ and perhaps others, but we insert the generator tag by default, so...

> I'm okay with removing it altogether.

Yeah, that one.

**Comment by rhcarvalho** [comment]
Done

**Comment by jmooring** [comment]
Thank you.

**Pull request merged**
