### PR TITLE
Revise homepage feature dynamic content claim

### PR DESCRIPTION
**Pull request by rdwatters**
See the following from a Hugo user for more background: https://discourse.gohugo.io/t/dynamic-api-driven-content/7499/8

### CODE REVIEW

**Comment by budparr** [comment]
Personally, I like the way it was and I'm not so sure this change doesn't present more questions than it answers. That said, if the original statement must go (that seemed to be @bep's direction), then perhaps just delete it (repeal and replace later <--bad joke).

**Comment by bep** [comment]
@budparr please don't push your PR branches to gohugoio; that will get messy very fast.

**Comment by bep** [comment]
Reopen on fork.

**Comment by budparr** [comment]
Okay @bep

**Comment by budparr** [comment]
@bep as this isn't my PR, I assume you're talking about my PR on the themes site: https://github.com/gohugoio/gohugoioTheme/pull/53 which I'm happy to redo as a fork.

**Comment by bep** [comment]
I'm talking about branches in this repo, which I get when I do a `git pull`... So, in general, we do branching from forks via PRs. So we have a limited set of branches in this repo. I deviated from this rule with my big "next" branch, but that was special. By pushing feature branches to this repo you create maintenance work, and you also push branches on people who doesn't really care about some "marketing copy" thing.

**Comment by budparr** [comment]
Thank you. I understand.

**Comment by rdwatters** [comment]
> (repeal and replace later <--bad joke)

#dadjokes (which I love, for the record) 😆 

But seriously, I'm okay with either option. Maybe adding a form of the word "flexibility" was a bit redundant too.

**Comment by bep** [comment]
Better than "capability", which I remember seeing more than once. :-)

**Comment by bep** [comment]
That said, I'm from Norway, but Isn't the "ity" form considered a little heavy, chancellery language. As in: "Flexible" would be better in most cases.

**Comment by rdwatters** [comment]
> That said, I'm from Norway

I've never been able to tell in any of our conversations. Your English is _fantastic_. 

Not sure what you mean by "chancellery" in this context&mdash;perhaps "uppity" or "highfalutin"&mdash;but the redundancy was between "Flexibility" rules and "flexible, data-driven content." 

If you ever find you're having difficulty falling asleep @bep, feel free to read the following: 

"Flexibility rules" is a complete sentence; i.e., there is a subject (the noun "flexibility") and a predicate (the present tense conjugation of the infinitive "to rule"). 

"Flexible rules" is an adjectival phrase and incomplete sentence (dependent clause); i.e., there is a pre-positive modifier (the adjective "flexible") of a plural noun ("rules"). 

Both are equally "correct," but for this case, the first makes more sense since it includes terminal punctuation; the "period" or "full stop." 

All said, marketing copy is very forgiving when it comes to prescriptive usage, and English is quirky as sh%#.

**Comment by jhabdas** [comment]
When I originally set out to create the site which I built After Dark for I'd intended to use hugo do dynamically drive the site based on a FaaS (e.g. Lambda). This is not a stretch to me as hugo is fast enough it could, for all intents and purposes, be considered dynamic IMHO.

http://bezdelev.com/post/hugo-aws-lambda-static-website/

**Comment by bep** [comment]
@jhabdas the problem isn't "how true it is", it is how the common man reads it ... wrong, and then we get questions on the forum, which want to avoid.

**Pull request closed without merging**
