### PR TITLE
Add RemoteTeam bio to showcase

### PR DESCRIPTION
**Pull request by mehmetkose**
Screen Shot 2020-07-13 at 15 03 15

### CODE REVIEW

**Comment by davidsneighbour** [comment]
> The featured.png is quite huge, is that normal or can you somehow squash it a bit more? The width in pixel does not seem too much, but it's unusually large for that.

Taking it back, it will be optimized on Netlify. Let it as it is. Remove the WIP in the title if you want this PR to be merged.

**Comment by mehmetkose** [comment]
> > The featured.png is quite huge, is that normal or can you somehow squash it a bit more? The width in pixel does not seem too much, but it's unusually large for that.
> 
> Taking it back, it will be optimized on Netlify. Let it as it is. Remove the WIP in the title if you want this PR to be merged.

Awesome! I think it's ready now. Thanks

**Comment by davidsneighbour** [comment]
Would you be OK with me rewriting it a little bit? The English can be improved and I would do that. No disrespect intended.

**Comment by mehmetkose** [comment]
well, I wrote this in a hurry. better I explain in a different way

**Comment by jmooring** [comment]
Stale, doesn't appear to be a Hugo site anymore, closing.

**Pull request closed without merging**
