### PR TITLE
Add `none` as a value for `layout`

### PR DESCRIPTION
**Pull request by robsonsobral**
Useful for FAQs, for example.

### CODE REVIEW

**Comment by digitalcraftsman** [comment]
Hi Robson,

great to see you again and thanks for opening this pull request :+1: To proceed please sign the CLA by clicking on the yellow badge in the comment above. It only has to be done once.

**Comment by bep** [comment]
I'm not a fan of this. It kind of works, and will continue so, but it will create a WARNING and we should not have tips in the docs that creates warnings ... This is a workaround, and until we get a better solution for this, these workarounds should live in the discussion forum, me thinks.

**Comment by robsonsobral** [comment]
> [...] we should not have tips in the docs that creates warnings [...]

It's a valid point, @bep . I totally agree. I can try to put a conditional to bypass the template lookup in case of `none`, but I never ever coded using GoLang.

I gonna take a look at this, but i don't know exactly when.

**Comment by digitalcraftsman** [comment]
Due to Bjørn Erik's comment and the possibility to handle this case in the code base of Hugo itself I'll close this issue.

**Pull request closed without merging**
