### PR TITLE
Add image actions

### PR DESCRIPTION
**Pull request by bep**
See https://github.com/gohugoio/hugoThemesSite/issues/64

### CODE REVIEW

**Comment by coliff** [comment]
Nice!  I'd suggest **losslessly** optimizing the images though (the default method). I think setting 'quality' to 80 will make some images look worse.

**Comment by bep** [comment]
OK, I guess I need to merge this first before anything can ...happen.

**Comment by bep** [comment]
Not sure what you mean, I just copied the default config and changed the ignore path:

https://github.com/marketplace/actions/image-actions#configuration

**Comment by bep** [comment]
I will do a test PR and see what happens ...

**Comment by coliff** [comment]
Yeah I think removing this part would be best:
```
jpeg:
  quality: 80
png:
  quality: 80
```
That way the config will be just set to ignore that path you added.

**Pull request merged**
