### PR TITLE
Iterating on Showcase

### PR DESCRIPTION
**Pull request by budparr**
I've cleanup up the single page template and re-arranged the page to make the navigation work better.

Reference #322

### CODE REVIEW

**Comment by bep** [comment]
The "Showcase" h1 title does not make much sense hanging there. I would just remove the h1 element.

**Comment by budparr** [comment]
May seem obvious to me and you where you're at, but I think people need wayfinding.

**Comment by bep** [comment]
>wayfinding

Can you elaborate on that ...?

**Comment by bep** [comment]
This looks very good:

**Comment by budparr** [comment]
Yeah, just letting people know where they are. It's quite clear in the docs, without say docs, but here it's just an image, basically.

**Comment by bep** [comment]
This looks untidy:

image

**Comment by budparr** [comment]
> Untidy
 
Are you still speaking of the "Showcase" heading?

**Comment by bep** [comment]
We can add showcase to the "<title>" element, but not alone in a h1 attribute.

**Comment by bep** [comment]
>Are you still speaking of the "Showcase" heading?

That is the only difference between the 2 screenshots.

**Comment by budparr** [comment]
Only seeing one screenshot. But at any rate, I disagree, but defer to you.

**Comment by budparr** [comment]
Done

**Pull request merged**
