### PR TITLE
Anaka theme uses /post/ and NOT /posts/

### PR DESCRIPTION
**Pull request by clemens-tolboom**
This should solve #862 

Not sure about the **asciicast** though :-(

### CODE REVIEW

**Comment by davidsneighbour** [comment]
This is the documentation for Hugo, not for the Anaka theme. Please re-open where ever this applies to.

**Comment by clemens-tolboom** [comment]
Ehm ... https://gohugo.io/getting-started/quick-start/#step-3-add-a-theme **adds** the theme then the page will never be displayed

**Comment by davidsneighbour** [comment]
Hmm, so the consensus seems to be that the folder should be the plural version of the post type but both versions (singular/plural) work. I would keep it consistent and maybe change the used sample theme for this or change it in Anaka?

@bep?

**Comment by clemens-tolboom** [comment]
The themes I checked (trying to use) did not have *concensus* neither on structure nor plural form :-(

- https://github.com/budparr/gohugo-theme-ananke/tree/master/exampleSite/content
- https://github.com/victoriadrake/hugo-theme-introduction/tree/master/exampleSite/content/en
- https://github.com/digitalcraftsman/hugo-artists-theme/tree/master/exampleSite
- https://github.com/okkur/syna/tree/master/exampleSite/content

So I guess we should allow this PR

BUT what about this **asciicast** ... can we get rid of that or is that auto generated?

**Comment by budparr** [comment]
When Hugo was created I recall the docs being specific about the folder being singular. I'll see if I can find that.

**Comment by clemens-tolboom** [comment]
@budparr would changing anaka not impact all anaka users in an unsuspected way (renaming folder(s)?

This PR is only to make the quickstart work properly ;-)

**Comment by budparr** [comment]
I don't think it would be a good idea to change Ananke because there are a fair number of users out there.

I can't find much of a trace of Steve's way of naming folders. It was formerly singular (as I recall), but now I see people are using plural (some changes from this year). Personally I think `site.com/post/post-name/` makes the most sense.

At the end of the day I think the docs outside of this particular how-to should be unopinionated about folder naming conventions, so it seems reasonable that themes would handle it differently

**Comment by bep** [comment]
So, what the main section(s) is named in a theme will wary; post/posts/blog/foo... So if you're doing a `where .Site.RegularPages ...` on the home page it's recommended to query by the `mainSections` param:

https://gohugo.io/functions/where/#mainsections

A user can set this in the config if he/she wants, but Hugo will do some page counting to determine what's considered "the main".

**Comment by bep** [comment]
So, I will not merge this. #862 is about something else, I think.

**Comment by clemens-tolboom** [comment]
I guess something went wrong ... the quick start does not funciton as **/posts/** are not 'rendered'

I should have filed a better summary :-( and refer to mentioned issue. My bad.

- https://gohugo.io/getting-started/quick-start/#step-4-add-some-content suggests to run `hugo new posts/my-first-post.md`
- https://gohugo.io/getting-started/quick-start/#step-5-start-the-hugo-server serves `anaka` based site which does not support `/posts/`

Thus this PR.

**Pull request closed without merging**
