### PR TITLE
don't hardcode https://gohugo.io/ to site name

### PR DESCRIPTION
**Pull request by agaengel**
don't hardcode https://gohugo.io/ to site name use / to get it working with hugo serve or hugo --gc --minify -b url

### CODE REVIEW

**Comment by bep** [comment]
As this theme is used on both themes.gohugo.io and gohugo.io, I don't think this fix will work as intened.

**Comment by agaengel** [comment]
ok I see is it possible to injetct the  baseurl in this case

**Comment by bep** [comment]
@agaengel I don't see how that would work, either.

**Comment by coliff** [comment]
A possible workaround solution (at least so it works on localhost) could be something like:

```html
{{- if not .Site.IsServer -}}
<a href="https://gohugo.io/" class="link white">
{{ else }}
<a href="/" class="link white">
{{ end }}
```

**Pull request closed without merging**
