### PR TITLE
Add roller2hugo to migrations.md

### PR DESCRIPTION
**Pull request by jlevon**

### CODE REVIEW

**Comment by jlevon** [comment]
anyone?

**Comment by jlevon** [comment]
ping?

**Comment by coliff** [comment]
That project has no stars and the README warns that it hasn't been thoroughly tested so maybe it night be better to not add it to this page yet?

**Comment by jlevon** [comment]
If there was an alternative to link to I'd agree 100%. Surely something is better than nothing?

**Comment by coliff** [comment]
Yep, maybe :-) . Let's see what @bep says.

**Comment by bep** [comment]
I think that people who really need this can Google for it.

**Comment by jlevon** [comment]
Then what's the point of the page at all?
BTW you tried googling for it?

**Pull request closed without merging**
