### PR TITLE
Create extensions.json

### PR DESCRIPTION
**Pull request by coliff**
Useful for contributors to the project to help ensure consistent code formatting

### CODE REVIEW

**Comment by davidsneighbour** [comment]
hmmmmmmmmmmmm. aren't you afraid the project will end up with similar files for other code editors? Maybe put a wholesome configuration (including .vscode directory) into an extra repository that people can load?

**Comment by coliff** [comment]
> hmmmmmmmmmmmm. aren't you afraid the project will end up with similar files for other code editors? Maybe put a wholesome configuration (including .vscode directory) into an extra repository that people can load?

I don't think so - VS Code is pretty dominant with approx 86% IDE market-share according a survey I saw. (https://2020.stateofjs.com/en-US/other-tools/#text_editors). I'm not aware of similar type of configs for recommended extensions for the others in the top 6. This is just a helpful tool to potentially aid contributors...

**Comment by bep** [comment]
>aren't you afraid the project will end up with similar files for other code editors?

I think @coliff is right, besides, VSCode has turned into my editor of choice for everything ... :-) I'm incredibly impressed about how that project has turned out (considering its heritage).

**Comment by davidsneighbour** [comment]
Yeah, see my comment in the discourse. I don't want to block anything, just having experiences that are too specific I think. VSCode has some more miles to go to be the god of open source, right now it's just great. Thinking about having a file ending on .HTML with JSON code in it under the content directory being treated as JSON with HTML in it. Maybe they will implement something that enables a per-directory content type sniffing. 

Anyway... Merge this. I just wanted to have made my mark for the obligatory "I told you so" in that alternate universe where I am right :D

**Pull request merged**
