### PR TITLE
taxonomies: fix yaml examples

### PR DESCRIPTION
**Pull request by sigma**
Align YAML examples with TOML ones.

### CODE REVIEW

**Comment by digitalcraftsman** [comment]
Hello @sigma,

first of all thanks for submitting this fix. In order to get your additions merged please sign the contributor license agreement by clicking on the yellow badge in the comment above. You've to do this only once.

**Comment by digitalcraftsman** [comment]
Any updates here?

**Comment by sigma** [comment]
@digitalcraftsman sorry about that. I'm currently going through a rather slow company process to be allowed to sign the DCO... I'll get it done

**Comment by digitalcraftsman** [comment]
Thank you for the update @sigma. There's nothing to apologize. Sometimes legal affairs take it's time

**Comment by sigma** [comment]
ok, everything is in order on my side (I hope! :))

**Comment by digitalcraftsman** [comment]
That was promptly! :+1:

**Pull request merged**
