### PR TITLE
docs: Add horeaporutiu.github.io to the showcase

### PR DESCRIPTION
**Pull request by horeaporutiu**

### CODE REVIEW

**Comment by horeaporutiu** [comment]
Add horeaporutiu.github.io to the showcase.

**Comment by digitalcraftsman** [comment]
Hello @horeaporutiu,

thank you for adding your website to the showcase of Hugo. I've merged your contribution as 309adec5.
Hugo's showcase section should be updated within the next minutes.

Cheers,
Digitalcraftsman

**Comment by horeaporutiu** [comment]
Hello @digitalcraftsman,

I have checked the https://gohugo.io/showcase/ site this morning and I have yet to see my contribution. I was wondering if there is some problem with my submission (I have heard my .gitignore file should have my name and email address associated with Github)?

Best,
Horea Porutiu

**Comment by digitalcraftsman** [comment]
Hello @horeaporutiu,

your commit was fine. So no problem on your end. When pushing a new commit to this repo a rebuild of the website should be triggered. However, I merged you commit into master. But the rebuild is only triggered for new commits on the stable branch.

@bep according to my proposal in #1 the stable branch is intended for the commits until the latest release. I.e. the stable branch will be referenced in the docs submodule when releasing a new version of Hugo.

The master branch on other hand can be updated between two releases and should be considered as the source for www.gohugo.io. I.e. it gets rebuild with a new commit on this branch.

I just want to clarify why we use `stable` as the source for www.gohugo.io?

**Comment by bep** [comment]
>I just want to clarify why we use stable as the source for www.gohugo.io?

Because `gohugo.io` represents a tagged version with potential additions that is correct for that tag. So when I released `v0.24.1` I reset the stable branch to that tag. So for any commits into master that is also relevant/correct for `v0.24.1` should be merged into `stable`.

It would make very little sense to have a docs site marked with `v0.24.1` and dump lots of 0.25 changes into it. Which is probably not what you described in your proposal, but `master` is by definition not stable, so I suggest we use the `dev` branch for bigger changes only (think: @rdwatters )

**Pull request closed without merging**
