### PR TITLE
Missing Translations section update

### PR DESCRIPTION
**Pull request by antonvasilev52**
I suggest to clarify that there is always a "default default language" when speaking about missing translations. A link to the **Configure Languages** section could also be useful.

### CODE REVIEW

**Comment by bep** [comment]
Isn't there a setting to insert some "missing translation" string? Might be relevant to add.

**Comment by antonvasilev52** [comment]
> Isn't there a setting to insert some "missing translation" string? Might be relevant to add.

 If you mean `enableMissingTranslationPlaceholders = true`, this option is mentioned just a bit below in the same chapter, so this point is clear in the docs.

**Review by davidsneighbour — APPROVED** [review]

**Comment by antonvasilev52** [comment]
@bep @davidsneighbour I am sorry if I don't quite understand how it works, but what else must be done to actually merge this change?  
You know the docs are usually 1) relatively easy to change than the code and 2) loose value when are outdated.

**Comment by jmooring** [comment]
See https://github.com/gohugoio/hugo/issues/9216. Neither the existing or proposed documentation matches the current behavior.

**Comment by bep** [comment]
I'm closing this for now, but thanks for the contribution.

**Pull request closed without merging**
