### PR TITLE
Update MathJax Tutorial with another method

### PR DESCRIPTION
**Pull request by rdtrimble**
I have added a third method of integrating MathJax, advantages are no longer requiring backticks or `<div>`s  to be entered and more natural rendered code. Disadvantages, it might make builds slightly longer?

### CODE REVIEW

**Comment by digitalcraftsman** [comment]
Hello @rdtrimble,

thanks for submitting this additions :+1: 

In the last days we added a contributor license agreement to this repository, like in the hugo repository. In order to sign the CLA please click on the black logo of the CLA bot in the "Some checks haven’t completed yet" block.

Just sign in with your GitHub account and click on accept. You only have to do this once, therefore this step can be omitted with future pull requests.

Regards,
Digitalcraftsman

**Comment by digitalcraftsman** [comment]
Any updates here?

**Comment by Hanzei** [comment]
Can this be closed?

**Comment by hanzei** [comment]
@kaushalmodi can this one be closed?

**Comment by kaushalmodi** [comment]
I haven't even reviewed this PR, because @rdtrimble still needs to sign the CLA.

**Pull request closed without merging**
