### PR TITLE
Add translation for search tools

### PR DESCRIPTION
**Pull request by LinuxSuRen**

### CODE REVIEW

**Comment by LinuxSuRen** [comment]
hi @anthonyfok Could you help me to review this PR?

**Comment by LinuxSuRen** [comment]
@bep This pr already pass a long time.

**Comment by LinuxSuRen** [comment]
I really hope to speed up the Chinese site, maybe we can figure out some kind of more efficient way.

**Comment by bep** [comment]
If @anthonyfok is OK with it, I can give you commit access to the docs repo.

**Comment by LinuxSuRen** [comment]
It's been a long time. I don't know how to push the process of localization.

**Comment by LinuxSuRen** [comment]
I guess that no one will response me. Just close it.

**Comment by LinuxSuRen** [comment]
Try to keep this active.

**Comment by davidsneighbour** [comment]
> If @anthonyfok is OK with it, I can give you commit access to the docs repo.

well... ;)

**Review by anthonyfok — APPROVED** [review]
Looks good to me!  Thank you @LinuxSuRen for your contribution!
My sincere apologies for taking so long to review and approve your pull request!

**Pull request merged**
