### PR TITLE
Fix quick-start.md commands for Windows

### PR DESCRIPTION
**Pull request by rotoglup**
Removed the `"` characters from `echo` commands : they end up in the `config.toml` file which becomes invalid

### CODE REVIEW

**Comment by jmooring** [comment]
@rotoglup Which of these did you use when entering the commands?

1. CMD
2. PowerShell
3. Windows PowerShell
4. WSL
5. Git Bash
6. Something else?

**Comment by rotoglup** [comment]
Oh, sure, it was CMD.

Le lun. 27 févr. 2023 à 16:00, Joe Mooring ***@***.***> a
écrit :

**Comment by jmooring** [comment]
@rotoglup 

Can you think of way to make this any clearer?




Screenshot 2023-02-27 075717

**Comment by rotoglup** [comment]
Sorry, I missed this section, I was too quick in my setup, and thought the whole document was a "getting started" for Windows.

I changed my commit to propose a change in the Windows-related note - trying to make it more apparent.

Sorry for the noise, feel free to reject this PR if you feel it is not helpful.

**Comment by jmooring** [comment]
I suggest instead:

```
**If you are a Windows user:**

- Do not use the Command Prompt
- Do not use Windows PowerShell
- Run these commands from [PowerShell] or a Linux terminal such as WSL or Git Bash

PowerShell and Windows PowerShell are different applications.

[PowerShell]: https://learn.microsoft.com/en-us/powershell/scripting/install/installing-powershell-on-windows
```

**Comment by rotoglup** [comment]
Fine for me, I updated the commit to include your text, so that you can merge the PR if you wish.

**Comment by jmooring** [comment]
Thank you for clarifying this.

**Pull request merged**
