### PR TITLE
Added tutorial videos to several doc pages

### PR DESCRIPTION
**Pull request by giraffeacademy**
I love what you guys are doing with Hugo! I made some tutorial videos that could be used on the docs.

Here's a link to the playlist on YouTube
https://www.youtube.com/playlist?list=PLLAZ4kZ9dFpOnyRlyS-liKL5ReHDcj4G3

### CODE REVIEW

**Comment by digitalcraftsman** [comment]
Hello @giraffeacademy,

thank you very much for taking the time to create an entire introduction series on Hugo :+1:
I had a quick look on your awesome series and it covers a lot of aspects that beginners are confronted with. 

I took the freedom and shared your link via Hugo's official [Twitter account](https://twitter.com/GoHugoIO/status/907327569829273601) and on [/r/gohugo](https://www.reddit.com/r/gohugo/comments/6zhr6o/new_introduction_series_on_how_to_kickstart_your/).

In order to merge your pull request please sign the CLA by clicking on the yellow badge in the comment above. Btw, you seem to use an email address for your commit that isn't known to GitHub meaning that the CLA bot can't associate your signing with your GitHub account.

Cheers,
Digitalcraftsman

**Comment by giraffeacademy** [comment]
Hey,

I had an issue signing the agreement (my initial commit wasn’t linked to an email) so I’m gonna open up a new pull request and sign it. I’ll do that right now

Thanks!

Mike Dane
Giraffe Academy

**Comment by digitalcraftsman** [comment]
You can also add the email address used in the commit to GitHub or change the email address via the command line.

**Comment by giraffeacademy** [comment]
Okay new request is in and all checks passed. Thanks for the help, sorry for the trouble!

Mike Dane
Giraffe Academy

**Comment by digitalcraftsman** [comment]
There's nothing to apologize, Mike.

**Pull request closed without merging**
