### PR TITLE
Unique Taxonomies for a Page added

### LINKED ISSUE #650: Example: Get unique tags/categories
Add an example to get unique tags/categories of a page.

See https://discourse.gohugo.io/t/get-all-unique-taxonomies-of-a-page/14431 for more information.

### PR DESCRIPTION
**Pull request by akshaybabloo**
See https://discourse.gohugo.io/t/get-all-unique-taxonomies-of-a-page/14431 for more information

resolves #650

### CODE REVIEW

**Comment by akshaybabloo** [comment]
Resolves #650

**Comment by kaushalmodi** [comment]
I'll get to this later this week (Wednesday).

**Comment by kaushalmodi** [comment]
There are a couple of things that I see need to be changed:

- use `.Pages` instead of `.Data.Pages`
- use `site` instead of `.Site`
- get rid of most of the variable assignment; just use the **dot** (`.`) .

**Comment by akshaybabloo** [comment]
Will update ths soon

**Comment by akshaybabloo** [comment]
still doing it

**Pull request closed without merging**
