### PR TITLE
Added external learning resources including Hugo In Action book.

### PR DESCRIPTION
**Pull request by atishay**
Looking for a place to link [Hugo In Action](https://www.manning.com/books/hugo-in-action) into the Hugo documentation website. This is a great place to have a discussion.

### CODE REVIEW

**Comment by bep** [comment]
Thanks, can you sign the CLA? If you have already, please check that the email address used for the commit is connected to your GitHub account (you can have multiple).

I agree that these external tutorials etc. don't fit naturally into the existing, but I need to think a little about the placement/structure.

**Comment by atishay** [comment]
Thanks. I have signed the CLA. Waiting for your thoughts.

**Comment by atishay** [comment]
@bep Waiting for your thoughts on this.

**Comment by atishay** [comment]
Bump to the top for a discussion. 

Happy to work on alternative suggestions.

**Comment by bep** [comment]
Sorry for the delay. I will merge this now. I still think we need to do a reorg of the content, but that can wait.

**Pull request merged**
