### PR TITLE
Function sort: fix example labels

### PR DESCRIPTION
**Pull request by chalin**
Preview: https://deploy-preview-1344--gohugoio.netlify.app/functions/sort/

### CODE REVIEW

**Comment by jmooring** [comment]
@chalin, the sample data on this page is wrong as well. Please update it to:

```
+++
tags = ["tag3", "tag1", "tag2"]
+++

// Site config
+++
[[params.authors]]
  id = "003"
  firstName = "Derek"
  lastName = "Perkins"
[[params.authors]]
  id = "001"
  firstName = "Joe"
  lastName = "Bergevin"
[[params.authors]]
  id = "002"
  firstName = "Tanner"
  lastName = "Linsley"
+++
```

Without these changes the sample code fails or provides the wrong results.

**Comment by jmooring** [comment]
See <https://github.com/gohugoio/hugo/issues/8335>.

**Comment by chalin** [comment]
@jmooring - thanks for your feedback. You beat me to adding the reference to issue https://github.com/gohugoio/hugo/issues/8335 :).

I fixed the list field name, changing it to `tags`.

As for `authors`, I believe that the example was meant to illustrate the sorting of a map. I've kept the map value, but swapped the first two entries.

Can we get this merged now and I'll revisit if/once https://github.com/gohugoio/hugo/issues/8335 is addressed?

**Comment by chalin** [comment]
cc @nate-double-u @zacharysarah

**Comment by jmooring** [comment]
Thoughts:

1. The documentation is currently wrong.
2. If we merge this the documentation will still be wrong, but a little less so.
3. gohugoio/hugo#8335 may never be addressed, in which case the documentation will remain wrong.

I'm OK merging this if you first create another issue in this repo that references gohugoio/hugo#8335. I don't want to forget that we have a documentation problem.

**Comment by chalin** [comment]
Done: #1365

**Pull request merged**
