### PR TITLE
Hugo Modules plural typo

### PR DESCRIPTION
**Pull request by fgiuliani**

### CODE REVIEW

**Comment by bep** [comment]
I'll leave this up to native English speakers to merge, but to me Go Modules is a feature, _one_ thing.

**Comment by fgiuliani** [comment]
@bep in the same file, in line 20

https://github.com/gohugoio/hugoDocs/pull/1266/files#diff-eb06e36138ce57f26402b557b85eda04b865d05f1d9698c17dfe3061edcda7a8L20

we have this

"Hugo Modules are the core building blocks in Hugo. A module can be your main project or a smaller module providing one or more of the 7 component types defined in Hugo: static, content, layouts, data, assets, i18n, and archetypes."

**Review by coliff — APPROVED** [review]

**Comment by moorereason** [comment]
I agree with @bep.  If we use the capitalized "Hugo Modules," treat it as a singular feature.

**Comment by coliff** [comment]
hmm - I'm almost 50/50 on this. :-|  I can see how it could be seen as both correct and incorrect...

**Comment by yaaax** [comment]
What about "Hugo Modules feature is powered by Go Modules" :) ?
_Disclaimer : I'm not a native English speaker_

**Comment by coliff** [comment]
@fgiuliani thanks for the PR and sorry for the delay :-)

**Comment by fgiuliani** [comment]
@coliff no problem. Thank you!

**Pull request merged**
