### PR TITLE
Update Quickstart examples to theNewDynamic theme repository

### PR DESCRIPTION
**Pull request by jan-xyz**
The repo for the example theme moved to a new URL and this PR fixes it.

### CODE REVIEW

**Review by davidsneighbour — APPROVED** [review]
A lot of pull requests fail or go unnoticed because the requester does not write a note about reasoning for the changes. It's not the reviewers task to check that ;)

Anyway. The theme repo moved to a new URL and this PR implements the new proper URL for the same theme.

**Comment by jan-xyz** [comment]
Ahh understood. Thank your the explanation! I will keep it in mind next time.

**Comment by jan-xyz** [comment]
Any thoughts on this?

**Comment by jmooring** [comment]
Looks good. Thank you!

**Pull request merged**
