### PR TITLE
Fix duplicated 'thanks for documentation contributions' in release notes

### PR DESCRIPTION
**Pull request by coliff**
and removed @kaushalmodi  - as per his request: https://github.com/gohugoio/hugoDocs/issues/1237#issuecomment-699014937

### CODE REVIEW

**Comment by bep** [comment]
The duplication comes from autogeneration, so I'd rather fix this in the code.

**Comment by coliff** [comment]
ah, ok - where is that code for us tp update then?

**Comment by bep** [comment]
So, the logic is in this area:

**Comment by jmooring** [comment]
Closing per #1240 (comment), new issue is gohugoio/hugo#8360.

**Pull request closed without merging**
