### PR TITLE
Updates pygments gallery link

### PR DESCRIPTION
**Pull request by bradryanbice**
Different link shows more options for pygments styles.

### CODE REVIEW

**Comment by kaushalmodi** [comment]
Hello, I just reviewed the links.. the old and new links are different.. older one is for Pygments themes and newer one is for Chroma themes, and they both are functional. So it doesn't justify removing the old link. Also the presentation of the old link is better.. all themes are visible on a single page.

If you are the developer of the new xyproto link, I was curious if you can make all themes visible on a single page..

As it stands, it doesn't seem worthy to removed the old, but working Pygments themes link.

**Comment by bradryanbice** [comment]
Fair enough. I'm not the developer of the page, just saw that most of those styles worked as well and thought it would be a helpful addition.

**Comment by bradryanbice** [comment]
@kaushalmodi FYI this link shows all the styles on one page: https://xyproto.github.io/splash/docs/all.html

**Comment by kaushalmodi** [comment]
[Really?][1] :P

[1]: https://github.com/xyproto/splash/issues/1

**Pull request closed without merging**
