### PR TITLE
git command to update submodule to latest

### PR DESCRIPTION
**Pull request by funkydan2**
This is how I update my themes. It took a while to find the commands that work, so I think it would be good to have them here for other users.

### CODE REVIEW

**Comment by funkydan2** [comment]
Hmm, not sure why the Netlify deploy fails on this PR. The change is just a few lines of markdown.

**Comment by funkydan2** [comment]
@hanzei Thanks. I've rebased my fork, but I'm not sure if the checks have been re-run.

**Comment by bep** [comment]
I merged it, not sure what's wrong with Netlify. A quick note: I use `git submodule update --remote --merge` for this same thing. The difference is `merge` vs `rebase` -- it kind of depends on the workflow, but I suspect `merge` is more common, not sure ...

**Comment by funkydan2** [comment]
I'm no git guru. That's the command I found on a stackoverflow discussion and it seems to work for me. Very happy for the docs to reflect a better practice.

**Pull request merged**
