### PR TITLE
Mention the significance of leading 0 in int fn string input

### PR DESCRIPTION
**Pull request by kaushalmodi**
https://discourse.gohugo.io/t/unable-to-cast-09-of-type-string-to-int/9614

### CODE REVIEW

**Comment by moorereason** [comment]
Can you also leave a hint about using `strings.TrimPrefix` to remove leading zeros?

**Comment by kaushalmodi** [comment]
@moorereason I prefer `replaceRE` as it is more robust. Use of `strings.TrimPrefix` needs to be hard-coded i.e. one needs to know exactly what string prefix needs to be removed.

### `replaceRE` examples

All of these work (tested)

```
            {{ int ("987" | replaceRE "^0+" "") }}
            {{ int ("0987" | replaceRE "^0+" "") }}
            {{ int ("00987" | replaceRE "^0+" "") }}
            {{ int ("000987" | replaceRE "^0+" "") }}
```

Note that the `replaceRE` expression can stay the exact same (`replaceRE "^0+" ""`) for any case.

### `strings.TrimPrefix examples

These work (tested):

```
            {{ int ("987" | strings.TrimPrefix "0") }}
            {{ int ("0987" | strings.TrimPrefix "0") }}
            {{ int ("00987" | strings.TrimPrefix "00") }}
```

But these don't (tested) as the prefix doesn't match exactly:

```
            {{ int ("00987" | strings.TrimPrefix "0") }}
            {{ int ("0987" | strings.TrimPrefix "000") }}
```

**Comment by kaushalmodi** [comment]
@moorereason I have updated this PR with `replaceRE` example, in case you'd like to move forward with that.

**Comment by moorereason** [comment]
My bad.  I should have said `strings.TrimLeft`.

**Comment by kaushalmodi** [comment]
@moorereason Done! Thanks for the review. The `strings.TrimLeft` is a good suggestion especially for folks not comfortable with regex. I did not know of that fn earlier.

*I know I will always reach out for `replaceRE` for cases like these 😄 *

BTW performance wise, is one better than another?

**Comment by moorereason** [comment]
The Trim funcs should be faster than RE.

**Comment by kaushalmodi** [comment]
@digitalcraftsman Can you please merge this?

**Comment by kaushalmodi** [comment]
@digitalcraftsman @bep Can you please merge this? Thanks.

**Pull request merged**
