### PR TITLE
Lint markdown; fix version and footnote; add examples

### PR DESCRIPTION
**Pull request by tohn**
I used [markdownlint](https://github.com/DavidAnson/markdownlint), but ignored [MD033](https://github.com/DavidAnson/markdownlint/blob/main/doc/Rules.md#md033) and [MD013](https://github.com/DavidAnson/markdownlint/blob/main/doc/Rules.md#md013) in the code lines.

Furthermore I fixed the version for type/section specific hooks and removed the footnote (since it's possible now).

And to complete the changes in Version 0.73.0, I added the `blog` example in the directory tree together with `render-heading.html`.

### CODE REVIEW

**Comment by bep** [comment]
So, the "max n chars per line" is something I would never do myself when writing Markdown, so we cannot have a linter that somehow complains about that.

**Comment by tohn** [comment]
> So, the "max n chars per line" is something I would never do myself when writing Markdown, so we cannot have a linter that somehow complains about that.

Ok. So should I revert the "max n chars per line" changes? Or is it fine for now, but should be excluded as proposed by #1102 (I saw this after I created this PR)?

**Comment by bep** [comment]
Let us conclude with #1102 before we start linting.

**Comment by tohn** [comment]
> Let us conclude with #1102 before we start linting.

Sounds good. I reverted the markdownlint changes.

**Comment by coliff** [comment]
hey @bep - the linting changes have been reverted, so is the content for this PR ok to be merged?

**Comment by tohn** [comment]
Hello, any news on this?

**Comment by jmooring** [comment]
This has been obsolete for a while. The render hook documentation has been moved and revised several times.

**Pull request closed without merging**
