### PR TITLE
Config toggle

### PR DESCRIPTION
**Pull request by regisphilibert**
Will comment in issue

### CODE REVIEW

**Comment by regisphilibert** [comment]
Next is old (7 Feb), this PR is a branch out of master, so I'd rather you guys merge it yourself rather than just me (odd feeling). Original branch from my fork is here: https://github.com/regisphilibert/hugoDocs/tree/config-toggle

**Comment by bep** [comment]
This PR has a Git history that I cannot (or will not) spend time on merging, I will only say this:

1) Rebase is your friend
2) The `next` branch is by definition experimental -- so you cannot ruin anything. But it helps to have a tidy Git history for when you want it to go into master.

**Comment by kaushalmodi** [comment]
@regisphilibert Looks like you had rebased config-toggle off master, so I just force pushed that to next.

Though, should we merge this directly into hugoDocs? Because a major chunk is the change in gohugoioTheme?

**Comment by bep** [comment]
>Though, should we merge this directly into hugoDocs? Because a major chunk is the change in gohugoioTheme?

That is a pragmatical approach and the benefit of the subtree approach. Once it looks good in hugodocs we can forward the changes to the theme.

**Comment by regisphilibert** [comment]
> That is a pragmatical approach and the benefit of the subtree approach. Once it looks good in hugodocs we can forward the changes to the theme.

My git self-confidence has never been so low (Kidding. Of course it has been).

I'm not sure on what I can rebase now that my branch already contains master's commit history though. 🤔

**Comment by kaushalmodi** [comment]
Also the js needs to be minified (which I just learned about: `npm run build:production` from https://github.com/gohugoio/gohugoioTheme/blob/master/src/readme.md).

**Comment by kaushalmodi** [comment]
@regisphilibert 

> I'm not sure on what I can rebase now that my branch already contains master's commit history though.

If this is about porting the hugoioTheme repo specific changes to that repo, I would just `cp -f` those files into that repo, then stage only the relevant parts, and discard the rest/outdated hunks.

.. and then minify the stuff in static/dist and commit everything.

**Comment by regisphilibert** [comment]
Ok, if I want to start clean what would be the best way to proceed ? Maybe not use a fork. 
1. branch from Next directly
2. rebase master on my newly created branch
3.  add toggle code
4. commit
5. push

**Comment by regisphilibert** [comment]
@kaushalmodi It's about the history of this PR. About the theme, I would need to know more about subtrees, never worked with those.

**Comment by kaushalmodi** [comment]
Btw this works: https://next--gohugoio.netlify.com/getting-started/code-toggle/

I haven't yet thoroughly checked but looks good.. the JS would be slow to load as it is unminified at the moment.

**Comment by regisphilibert** [comment]
@kaushalmodi How come it works without the PR working ? 🤔

**Comment by bep** [comment]
That looks great! 

And even more fantastic if we could kind get rid the flicker effect on "remembering the tab".

**Comment by regisphilibert** [comment]
> And even more fantastic if we could kind get rid the flicker effect on "remembering the tab".

Yes we had a lengthy exchange about that remember ? :)

There's no easy fix. We could hide the code-toggles until we have shown the saved pane. But there would still be a kind of flick.

If any one has suggestions, I take them!

**Comment by regisphilibert** [comment]
Question: What is the best process when working on hugoioTheme ? Working on right here in hugoDocs or in the theme's repo ?

**Comment by bep** [comment]
>If any one has suggestions, I take them!

I will think about it, but it is a minor detail. This is a big, big improvement to what we have.

**Comment by regisphilibert** [comment]
Ok I still have a lot of stuff to learn git wise...
You guys don't have to spend too much time explaining to me, but I'll summarize what I figured out. And you can come back to it when/if you have the time:

@kaushalmodi just singled out my commit from the PR and pushed it to Next ?
It has not been merged to the theme yet, so for now I'll keep improving my code from within hugoDocs' next branch.
Then we'll merge hugoDocs/themes/gohugoioTheme back to the theme's repo when done. (Curious to see how this step works)

**Comment by regisphilibert** [comment]
I'll close the PR. Please see my notes on https://github.com/gohugoio/hugoDocs/issues/363 for further specing / suggestions.

**Comment by kaushalmodi** [comment]
@regisphilibert 

> How come it works without the PR working ?

I just stole your Github keys :P j/k

*Github PR system is what Microsoft Word is to plain text documentation.. More frills, less power.* 

So I just fetch your remote and play with the commits locally, and then I can (force) push that to whatever branch on whatever remote where I can commit access.

> just singled out my commit from the PR and pushed it to Next ?

This is how all commits look to me:

image

- regis/master was on upstream/master~1, and regis/config-toggle was based off that.
- So I created a local branch off regis/config-toggle and rebased it off upstream/master.
- Then I checked out my local next branch and force reset it to my local config-toggle
- .. and force pushed that to upstream/next (which Netlify picked up to build that preview)

**Comment by regisphilibert** [comment]
Thank you so much for the explanation @kaushalmodi ! Always nice to learn new stuff.

**Pull request closed without merging**
