### PR TITLE
Add draft statement to FAQ

### PR DESCRIPTION
**Pull request by RickCogley**
Questions re "my content is invisible" are coming up a lot in the Discourse. Add a point about draft mode.

### CODE REVIEW

**Comment by bep** [comment]
Yes, this belongs there. But a note for future "I want to add to the FAQ section" people: There is a reason why the FAQ is short. It should be.

**Comment by RickCogley** [comment]
Thanks


-- 
*This email message and any attachments are confidential, and are meant to 
be read by the intended recipient only. If you are not the intended 
recipient, we would request you delete this message or any attachments 
without reading or distributing, and kindly advise eSolia Inc. (contacts: 
esolia.com/about <http://esolia.com/about>). Thank you in advance.*

**Comment by StephenBrown2** [comment]
But if it is in fact a frequently asked question, it should be in the FAQ. I prefer first searching a long FAQ page that gives links to further documentation than trying to dig through the docs on my own.

**Comment by bep** [comment]
>But if it is in fact a frequently asked question, it should be in the FAQ. 

Yes. But I just want us to be a little bit critical to what we put there. The goal is to make people stop asking it: Maybe it is better to improve the original section about the topic.

**Pull request merged**
