### PR TITLE
improve dates i18n workaround

### PR DESCRIPTION
**Pull request by gdeshors**
The existing one worked only when you had one language. This proposal works with several languages.

### CODE REVIEW

**Comment by gdeshors** [comment]
(in reply to the pull request being stalled) I like my proposal because I spent quite some time figuring out how to do it for myself, hence I'd like to share it with future readers.

**Comment by davidsneighbour** [comment]
This pull request is a solution that better lives in [the Tips and Tricks section](https://discourse.gohugo.io/c/tips-tricks/) of the Hugo Forum. You replace a one-language solution with a multi-language solution and by the way remove the `time` tag.

**Comment by gdeshors** [comment]
You're right about me removing the time tag, this is an error, thanks for pointing it out. Do I have a way to edit my pull request ?
Apart from that, a multi-language solution still seems better to me than a one-language one, and if it was my need, I may not be alone.

**Comment by davidsneighbour** [comment]
Any commits to the branch you merge in this pull request will be added to the pull request.

**Pull request closed without merging**
