### PR TITLE
Add video to quick start guide

### LINKED ISSUE #1906: Use VHS to create animated WebP images for quick tutorial (and possibly others)
See https://github.com/charmbracelet/vhs

Asciicast was recently removed (I agree about that decision). Having some illustrative CLI animations does look good, though, and they have some documentation value.

I have tested VHS briefly and:

* It's a little bit of a hassle to install (Brew installed without hickups, but it seem to have lots of dependencies)
* The end result looks great.
* One great thing about it is that they're created from a simple text based DSL language, meaning it can be easily redone with new Hugo versions.

### PR DESCRIPTION
**Pull request by jmooring**
Closes #1906

Using [github.com/charmbracelet/vhs](https://github.com/charmbracelet/vhs/), this places a responsive HTML video element on the page: WebM with an MP4 fallback. 

Advantage of video over animated GIF:
- Smaller file size (at least with this 34s video)
- Users can pause with video controls
- We can control autoplay, loop, whether or not to show the playback controls, etc.
- Full screen mode is one of the playback controls.

The video shortcode is, for now, limited to page resources. 

Files (16:9, 1024x576)

```
628K quickstart.mp4
584K quickstart.webm
```

I'm not entirely happy with the file sizes, but they're probably OK. The `.tape` file is checked into source control, adjacent to the video files. It can serve as a template for future use.

I probably went through 20+ iterations to refine this. The only complaint that I have about VHS is that the Sleep period (pause between commands) doesn't always do what you think it should do. It seems to depend on frame rate and perhaps the time required for the command to complete. Fixing this is the [most liked issue](https://github.com/charmbracelet/vhs/issues/70).

Lighthouse performance score is 100 for this page.

Preview: <https://deploy-preview-1908--gohugoio.netlify.app/getting-started/quick-start/>

### CODE REVIEW

**Review by coliff — APPROVED** [review]

**Comment by coliff** [comment]
video looks great and format works well I think.
I wonder if the video should be a bit lower down in the page though as a user should read the prerequisites first?

**Comment by bep** [comment]
I get a lot of

```bash
~/d/g/g/h/c/e/g/quick-start ❯❯❯ vhs < quickstart.tape                                                                 add-video-to-getting-started ◼
 38 │ Type `echo "theme = 'ananke'" >> config.toml`
           ^ Type expects string

 38 │ Type `echo "theme = 'ananke'" >> config.toml`
           ^ Invalid command: `

 38 │ Type `echo "theme = 'ananke'" >> config.toml`
            ^^^^ Invalid command: echo
```

Trying to build the tape.

But if if I replace that line with a dummy command and create a GIF using the same settings:

image

What's the size of the GIF when you build it?

Note that I don't mind one or 2 500KB images/videos in there, but I think these _kinds_ of videos have mostly an illustrative value, and they could probably even be scaled smaller and still have that illustrative value.

**Comment by jmooring** [comment]
Backticks as quotes were added a few days ago with [7ffc5f8f](https://github.com/charmbracelet/vhs/commit/7ffc5f8fb0416cb33bd6e296a8b08d8f3809a030).

The GIF is 1.2 MB.

**Comment by bep** [comment]
OK, I fail to run the latest VHS version (ttyd 1.7.2 not yet available on Brew). I suggest we wait a little with this one until then.

**Comment by jmooring** [comment]
I'm fine with holding off. This was just an experiment.

One more test, at 640x360.

```
712K quickstart.gif
360K quickstart.mp4
364K quickstart.webm
```

The file sizes vary by 2-3% on each run.

At this size, when viewed at 100%, the font is a bit fuzzy. I was trying to find a middle ground so that it would look decent on the desktop, mobile, and in full screen mode (the later being less of a priority).

I'm not sure that a 37% reduction in WebM size is worth the loss in quality.

**Pull request closed without merging**
