### PR TITLE
zh: Translate /documentation.md and /_index.md

### PR DESCRIPTION
**Pull request by renyifu**
documentation&index

### CODE REVIEW

**Comment by anthonyfok** [comment]
@renyifu Two more things:

1. Please sign the CLA (Contributor License Agreement), otherwise we are unable to accept your contribution.

2. Please improve your git commit message.  I recommend changing your current

    ```
    ZH'changes

    documentation&index
    ```

    to

    ```
    Translate /documentation.md and /_index.md to Chinese
    ```

    or

    ```
    zh: Translate /documentation.md and /_index.md
    ```

    See https://github.com/gohugoio/hugo/blob/master/CONTRIBUTING.md for more information about Git Commit Message Guidelines.

Thank you!

**Comment by anthonyfok** [comment]
Thank you for your revisions, @renyifu!

There are a few remaining issues, e.g. 中文顿号、逗号前后不必加空格 (No need for extra space between Chinese full-width comma (Dunhao); space should be added outside of half-width (ASCII) parentheses but not inside...  But these are minor issues that I will fix in a subsequent commit.

I will merge your contribution soon, after I have merged two other Chinese translation contributions that were submitted in May or June.

Cheers,
Anthony

**Comment by digitalcraftsman** [comment]
@anthonyfok since you approved the changes do you think this pull request is ready to be merged?

**Comment by anthonyfok** [comment]
@renyifu Thank you for your contribution!  And my sincere apologies for taking so long to follow-up.

**Pull request closed without merging**
