### PR TITLE
Update data-templates.md

### PR DESCRIPTION
**Pull request by XhmikosR**
Fix anchor to `#call-the-functions-with-a-url`

### CODE REVIEW

**Comment by XhmikosR** [comment]
BTW wouldn't this be better if there was a shortcode or something so that build would fail?

**Comment by kaushalmodi** [comment]
> BTW wouldn't this be better if there was a shortcode or something so that build would fail?

I think only running a link checker would help here. We do not have link checking enabled in the CI yet. May be this deserves a discussion in a separate hugoDocs issue.

**Comment by XhmikosR** [comment]
I was referring to using `ref``relref` to link to internal pages/anchors.

**Comment by kaushalmodi** [comment]
I tried that but that doesn't error out on broken anchors.

**Comment by XhmikosR** [comment]
True. Not sure if this could be implemented.

**Comment by XhmikosR** [comment]
BTW you could give [linkinator](https://github.com/JustinBeckwith/linkinator) a go. We are using it on Bootstrap, it's pretty fast, but I doubt it checks anchors either.

**Comment by kaushalmodi** [comment]
I have been using https://github.com/wjdp/htmltest (again, don't think that checks anchors either).

**Comment by XhmikosR** [comment]
It seems htmltest does support anchors

>a: Whether internal hashes work.

**Pull request merged**
