### PR TITLE
csv & json files location outside of data/

### PR DESCRIPTION
**Pull request by divinerites**

### CODE REVIEW

**Comment by kaushalmodi** [comment]
Can you please elaborate on this PR? Why is that statement needed? 

Would be good if you can document a use case in this thread so that we understand the motive of this change.

**Comment by divinerites** [comment]
No problem :-)

CSV files can be processed but they need to be outside of /data/ folder. (see https://discourse.gohugo.io/t/error-message-failed-to-read-data-from-csv-even-it-is-working-fine/10763/7).

On this documentation page data-template.md, this fact is not clear. We talk about YAML, JSON, or TOML in data folder. Then after that we talk abour CSV files via getCSV, but it make the CSV file location ambigus.

So I propose to make a clear statement (and you have to edit my giblish so called english :-) that CSV should be located outside of data folder.

**Comment by divinerites** [comment]
Ahhhh, and reading me again, I guess only the csv file (json is fine) should be outside of /data/. Sorry.

**Comment by kaushalmodi** [comment]
@divinerites Thanks! I have reworded that and moved it to a different location in the doc; commited in https://github.com/gohugoio/hugoDocs/commit/f462b620f38b9ccd81b544c609fd9a344b254479.

**Pull request closed without merging**
