### PR TITLE
Support Qovery as a deployment option

### PR DESCRIPTION
**Pull request by arnaudjnn**
Hi Hugo team,

I added docs on deploying Hugo to Qovery - feedback is welcome.

Arnaud.

### CODE REVIEW

**Comment by arnaudjnn** [comment]
Hi Hugo team,

Do you need more infos regarding this deploy option?

Let me know,

**Comment by coliff** [comment]
For reference:
Alexa rank: #327,292
https://www.alexa.com/siteinfo/qovery.com

@hugo-docs team: 
We already have a lot (too many?) hosting guides for companies and can't add guides for every hosting company. Perhaps we should define a minimum Alexa rank for submissions....

**Review by jmooring — COMMENTED** [review]
There have been several attempts to get this into the Gatsy documentation. None of the PR's have been accepted:

- <https://github.com/gatsbyjs/gatsby/pull/22515>
- <https://github.com/gatsbyjs/gatsby/pull/22516>
- <https://github.com/gatsbyjs/gatsby/pull/29314>
- <https://github.com/gatsbyjs/gatsby/pull/30262>

My [comments on PR #1429](https://github.com/gohugoio/hugoDocs/pull/1429#pullrequestreview-642460510) are applicable here as well.

I recommend closing this PR.

**Comment by bep** [comment]
Hey, and thanks for this.

I think I'm saying that we are currently not adding any more "deployment options/guides" to the documentation site unless it can provide an obvious and useful Hugo link. We need to take a step and look at the deployment options/guides we already have -- I'm starting to feel that we have become this marketing site for new host options. We should probably trim down what we have, but let's start by taking a pause with adding others.

**Comment by evoxmusic** [comment]
> There have been several attempts to get this into the Gatsy documentation. None of the PR's have been accepted:
> 
>     * [gatsbyjs/gatsby#22515](https://github.com/gatsbyjs/gatsby/pull/22515)
> 
>     * [gatsbyjs/gatsby#22516](https://github.com/gatsbyjs/gatsby/pull/22516)
> 
>     * [gatsbyjs/gatsby#29314](https://github.com/gatsbyjs/gatsby/pull/29314)
> 
>     * [gatsbyjs/gatsby#30262](https://github.com/gatsbyjs/gatsby/pull/30262)
> 
> 
> My [comments on PR #1429](https://github.com/gohugoio/hugoDocs/pull/1429#pullrequestreview-642460510) are applicable here as well.
> 
> I recommend closing this PR.

What's the point with Gatsby?

**Comment by evoxmusic** [comment]
> Hey, and thanks for this.
> 
> I think I'm saying that we are currently not adding any more "deployment options/guides" to the documentation site unless it can provide an obvious and useful Hugo link. We need to take a step and look at the deployment options/guides we already have -- I'm starting to feel that we have become this marketing site for new host options. We should probably trim down what we have, but let's start by taking a pause with adding others.

Thank you Bep for your feedback. Just to make things clear, we are not charging developers for free hosting - [check out this reddit post](https://www.reddit.com/r/Python/comments/mnbrrk/tutorial_how_to_host_for_free_your_python_app/) with +750 upvotes. This is not a scam and we have 100% transparent. We can make Hugo available to our 2445 dev community from 110+ countries. Let me know if you change your mind.

Romaric - CEO and co-founder of Qovery.

**Pull request closed without merging**
